SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE FUNCTION [dbo].[RETURN_AIRPORT](@ID_COUNTRY CHAR(2)) --RECIBIR ID DE UN PAIS DETERMINADO
RETURNS NVARCHAR(3)
AS
BEGIN
	DECLARE @AIRPORT NVARCHAR(3) --ALMACENA EL CODIGO DEL AEROPUERTO DONDE MAS VUELOS SALEN (DESTINOS DIFERENTE)
	SELECT TOP 1 @AIRPORT = A.iata_airport_code
	FROM COUNTRY C INNER JOIN AIRPORT A ON C.iata_country_code = A.iata_country_code
	INNER JOIN DIRECTION D ON A.iata_airport_code = D.origin_iata_airport_code
	WHERE C.iata_country_code = @ID_COUNTRY
	GROUP BY A.iata_airport_code
	ORDER BY COUNT(A.iata_airport_code) DESC

	RETURN @AIRPORT
END
GO


