SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE FUNCTION [dbo].[SEATS_SOLD](@FLIGHT_CALL INT) --RECIBE EL NUMERO DE VUELO
RETURNS MONEY --RETORNA EL TOTAL EN DINERO ($) DE ASIENTOS VENDIDO
AS
BEGIN
	DECLARE @SUM MONEY
	SELECT @SUM = SUM(F.price_usd) --ALMACENA LA SUMA DE LOS PRECIOS DE LOS ASIENTOS (DE EL VUELO "@FLIGHT_CALL")
	FROM BOOKING B INNER JOIN FLIGHTSEATPRICE F ON B.FLIGHT_CALL = F.FLIGHT_CALL AND B.AIRCRAFT_ID = F.AIR_CRAFT_ID AND B.Seat_ID = F.seat_ID
	WHERE B.FLIGHT_CALL = @FLIGHT_CALL

	RETURN @SUM
END
GO


