SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE FUNCTION [dbo].[MOST_VISITED_COUNTRIES](@CLIENT_ID INT) --RECIBE EL ID DE UN CLIENTE DETERMINADO
RETURNS CHAR(2) --RETORNA EL PAIS DONDE MAS HA VIAJADO
AS
BEGIN
	DECLARE @COUNTRY CHAR(2) --ALMACENA EL ID DEL PAIS

	SELECT TOP 1 @COUNTRY = A.IATA_COUNTRY_CODE
	FROM BOOKING B INNER JOIN FLIGHT F ON B.FLIGHT_CALL = F.FLIGHT_CALL
	INNER JOIN SCHEDULE S ON F.SCHEDULE_ID = S.SCHEDULE_ID
	INNER JOIN AIRPORT A ON S.DEST_IATA_AIRPORT_CODE = A.IATA_AIRPORT_CODE
	WHERE B.CLIENT_ID = @CLIENT_ID AND F.FLIGHT_STATUS_ID = 7 --DONDE EL ESTATUS DEL VUELO ES IGUAL A 'COMPLETADO (7)'
	GROUP BY A.IATA_COUNTRY_CODE
	ORDER BY COUNT(A.IATA_COUNTRY_CODE) DESC

	RETURN @COUNTRY
END
GO


